apiVersion: apps/v1
kind: Deployment
metadata:
  name: fileapp-deployment
  labels:
    app: fileapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fileapp
  template:
    metadata:
      labels:
        app: fileapp 
    spec:
      containers:
      - name: nodeserver
        image: bhavika2881/file:master
        ports:
        - containerPort: 5500
